name: Restic

on:
  push:
    branches:
      - main
    paths:
      - 'restic/**'
      - .github/workflows/restic.yml
  workflow_dispatch:

# env:
#   REGISTRY: ghcr.io
#   IMAGE: ${{ github.repository }}/restic

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hardened Images
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "abihf/github-abihf-images"

      - name: Build and push image (latest, sha)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./restic
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/restic:latest
            ghcr.io/${{ github.repository }}/restic:${{ github.sha }}
          platforms: linux/amd64
          outputs: type=registry,oci-mediatypes=true,compression=zstd,force-compression=true

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository }}/restic
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
