name: Scan Container Images

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'adguardhome'
          - 'overseerr'
          - 'plex'
          - 'prowlarr'
          - 'qbittorrent'
          - 'radarr'
          - 'restic'
          - 'sabnzbd'
          - 'sonarr'
          - 'speedtest'
    steps:
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          # severity: 'CRITICAL,HIGH'
          # exit-code: '1' # Fails the workflow if critical/high vulnerabilities are found

      - name: Upload Trivy scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'