name: Scan Container Images

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'

jobs:
  listapp:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.list.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: List all container images in the repository
        id: list
        run: |
          images="$(ls */Dockerfile | xargs -n1 dirname | jq -R -s -c 'split("\n") | map(select(length > 0))')"
          echo "images::$images" >> $GITHUB_OUTPUT
  scan:
    runs-on: ubuntu-latest
    needs: listapp
    permissions:
      security-events: write
      packages: read
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.listapp.outputs.images) }}
    steps:
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fails the workflow if critical/high vulnerabilities are found

      - name: Upload Trivy scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'