name: Update All Images

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update all images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run update scripts
        run: bash update-all.sh
        env:
          PLEX_PASS: ${{ secrets.PLEX_PASS }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated image updates"
          branch: main
          file_pattern: '**/Dockerfile'