name: Update All Images

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0,3,5'

jobs:
  update:
    name: Update all images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}

      - name: Run update scripts
        run: bash update-all.sh
        env:
          PLEX_PASS: ${{ secrets.PLEX_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate commit message
        id: message
        run: |
          apps="$(git diff --name-only | cut -d/ -f1 | sort | uniq | paste -s -d' ')"
          echo "msg=update: ${apps}" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "${{ steps.message.outputs.msg }}"
          branch: main
          file_pattern: '**/Dockerfile'
